# Generated by Django 5.1.3 on 2024-11-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=11)),
                ('speciality', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('не подтверждено', 'Не подтверждено'), ('подтверждено', 'Подтверждено'), ('отклонено', 'Отклонено')], default='не подтверждено', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('обработан', 'Обработан'), ('отклонен', 'Отклонен')], default='новый', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military_units.doctor')),
                ('military_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military_units.militaryunit')),
            ],
        ),
    ]
