# Generated by Django 5.1.3 on 2024-11-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanitarianAidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('ожидание', 'Ожидание'), ('одобрено', 'Одобрено'), ('отклонено', 'Отклонено')], default='ожидание', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('military_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military_units.militaryunit')),
            ],
        ),
    ]
